export const WALLET_ACTION_TYPES = {
    CREATE_SUCCESS: 'CREATE_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
}

export const WALLET_STATUS = {
    NOT_REGISTERED: 'NOT_REGISTERED',
    NOT_AUTH: 'NOT_AUTH',
    IS_AUTH: 'IS_AUTH',
    IS_LOCKED: 'IS_LOCKED',
    CHECKING_REGISTERED: 'CHECKING_REGISTERED'
}