# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LibertasMobile' do
  rn_path = '../node_modules/react-native'
  
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'BatchedBridge'
  ]
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'Firebase/RemoteConfig'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end
