const _instance = {
    backspace: require('../assets/icon/backspace.png'),
    back: require('../assets/icon/Back.png'),
    bell: require('../assets/icon/bell-icon.png'),
    close: require('../assets/icon/close.png'),
    cloud_down: require('../assets/icon/Cloud down 2.png'),
    cloud_up: require('../assets/icon/Cloud Up 2.png'),
    decrease: require('../assets/icon/decrese.png'),
    dropdown: require('../assets/icon/dropdown.png'),
    edit: require('../assets/icon/edit.png'),
    factory: require('../assets/icon/factory.png'),
    file: require('../assets/icon/file.png'),
    increase: require('../assets/icon/increase.png'),
    key2: require('../assets/icon/Key 2.png'),
    key: require('../assets/icon/key.png'),
    menu: require('../assets/icon/menu.png'),
    new_chat: require('../assets/icon/new_chat.png'),
    notification_badge: require('../assets/icon/NotificationBadge.png'),
    notification: require('../assets/icon/Notification.png'),
    order_placed: require('../assets/icon/Order Placed Style.png'),
    photo: require('../assets/icon/photo-icon.png'),
    qr: require('../assets/icon/QR.png'),
    receive: require('../assets/icon/receive.png'),
    right_arrow: require('../assets/icon/right arrow.png'),
    send: require('../assets/icon/send.png'),
    share: require('../assets/icon/share.png'),
    smartphone: require('../assets/icon/smartphone-icon.png'),
    wallet: require('../assets/icon/wallet.png'),
    widget: require('../assets/icon/widget.png'),
    words: require('../assets/icon/words.png'),
}

export default _instance