
// Objective-C API for talking to the following Go packages
//
//	libertas-crypto/crypto
//	libertas-crypto/steganos
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Crypto_FRAMEWORK_H__
#define __Crypto_FRAMEWORK_H__

#include "Crypto.objc.h"
#include "Steganos.objc.h"
#include "Universe.objc.h"

#endif
