// Objective-C API for talking to libertas-crypto/crypto Go package.
//   gobind -lang=objc libertas-crypto/crypto
//
// File is generated by gobind. Do not edit.

#ifndef __Crypto_H__
#define __Crypto_H__

@import Foundation;
#include "Universe.objc.h"


@class CryptoAesCryptor;
@protocol CryptoCryptor;
@class CryptoCryptor;

@protocol CryptoCryptor <NSObject>
- (NSData*)decrypt:(NSString*)k input:(NSData*)input;
- (NSData*)encrypt:(NSString*)k input:(NSData*)input;
@end

@interface CryptoAesCryptor : NSObject <goSeqRefInterface, CryptoCryptor> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (BOOL)disableNorm;
- (void)setDisableNorm:(BOOL)v;
- (NSData*)decrypt:(NSString*)k input:(NSData*)input;
- (NSData*)encrypt:(NSString*)k input:(NSData*)input;
@end

FOUNDATION_EXPORT NSData* CryptoMd5(NSData* data);

FOUNDATION_EXPORT NSData* CryptoSha1(NSData* data);

FOUNDATION_EXPORT NSData* CryptoSha256(NSData* data);

FOUNDATION_EXPORT NSData* CryptoSha512(NSData* data);

@class CryptoCryptor;

@interface CryptoCryptor : NSObject <goSeqRefInterface, CryptoCryptor> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSData*)decrypt:(NSString*)k input:(NSData*)input;
- (NSData*)encrypt:(NSString*)k input:(NSData*)input;
@end

#endif
