// Objective-C API for talking to libertas-crypto/steganos Go package.
//   gobind -lang=objc libertas-crypto/steganos
//
// File is generated by gobind. Do not edit.

#ifndef __Steganos_H__
#define __Steganos_H__

@import Foundation;
#include "Universe.objc.h"


@class SteganosJPEGByteArrayReader;
@class SteganosJPEGFileReader;
@class SteganosJPEGStegano;
@class SteganosSegment;
@class SteganosUnSupportedFileError;
@protocol SteganosExifReader;
@class SteganosExifReader;
@protocol SteganosStegano;
@class SteganosStegano;

@protocol SteganosExifReader <NSObject>
- (NSData*)readBytes:(long)n error:(NSError**)error;
- (SteganosSegment*)readSegment:(NSError**)error;
- (BOOL)readUint16:(long*)ret0_ error:(NSError**)error;
- (BOOL)readUint32:(long*)ret0_ error:(NSError**)error;
@end

@protocol SteganosStegano <NSObject>
- (NSData*)hide:(NSData*)image data:(NSData*)data error:(NSError**)error;
- (NSString*)readFile:(NSString*)path;
- (NSData*)readHidden:(NSData*)image error:(NSError**)error;
@end

@interface SteganosJPEGByteArrayReader : NSObject <goSeqRefInterface, SteganosExifReader> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)readBytes:(long)n error:(NSError**)error;
- (SteganosSegment*)readSegment:(NSError**)error;
- (BOOL)readUint16:(long*)ret0_ error:(NSError**)error;
- (BOOL)readUint32:(long*)ret0_ error:(NSError**)error;
- (void)seek:(long)offset;
@end

@interface SteganosJPEGFileReader : NSObject <goSeqRefInterface, SteganosExifReader> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)readBytes:(long)n error:(NSError**)error;
- (SteganosSegment*)readSegment:(NSError**)error;
- (BOOL)readUint16:(long*)ret0_ error:(NSError**)error;
- (BOOL)readUint32:(long*)ret0_ error:(NSError**)error;
- (void)seek:(long)offset;
@end

@interface SteganosJPEGStegano : NSObject <goSeqRefInterface, SteganosStegano> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)hide:(NSData*)image data:(NSData*)data error:(NSError**)error;
- (NSString*)readFile:(NSString*)path;
- (NSData*)readHidden:(NSData*)image error:(NSError**)error;
@end

@interface SteganosSegment : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)magicData;
@end

@interface SteganosUnSupportedFileError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)error;
@end

FOUNDATION_EXPORT const int64_t SteganosBUFFER_SIZE;
FOUNDATION_EXPORT const int64_t SteganosEOI;
FOUNDATION_EXPORT const int64_t SteganosSEGMENT_IDENTIFIER;
FOUNDATION_EXPORT const int64_t SteganosSEG_LIBERTAS;
FOUNDATION_EXPORT const int64_t SteganosSOI;

FOUNDATION_EXPORT SteganosSegment* SteganosCreateLibertasSegment(NSData* data);

FOUNDATION_EXPORT SteganosSegment* SteganosCreateSegment(BOOL isHeader, long size, NSData* data);

FOUNDATION_EXPORT SteganosUnSupportedFileError* SteganosCreateUnSupportedFile(NSString* fileType);

@class SteganosExifReader;

@class SteganosStegano;

@interface SteganosExifReader : NSObject <goSeqRefInterface, SteganosExifReader> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSData*)readBytes:(long)n error:(NSError**)error;
- (SteganosSegment*)readSegment:(NSError**)error;
- (BOOL)readUint16:(long*)ret0_ error:(NSError**)error;
- (BOOL)readUint32:(long*)ret0_ error:(NSError**)error;
@end

@interface SteganosStegano : NSObject <goSeqRefInterface, SteganosStegano> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSData*)hide:(NSData*)image data:(NSData*)data error:(NSError**)error;
- (NSString*)readFile:(NSString*)path;
- (NSData*)readHidden:(NSData*)image error:(NSError**)error;
@end

#endif
